[tools]
terraform = "latest"
usage = "latest"

[settings]
legacy_version_file = true
idiomatic_version_file_enable_tools = ["ruby"]

# config files with these prefixes will be trusted by default
trusted_config_paths = [
    "~/.dotfiles/mise",
]
